
create table IF NOT EXISTS users (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar NOT NULL,
login varchar NOT NULL,
user_name varchar,
birthday timestamp NOT NULL
);

create table IF NOT EXISTS friendship (
friendship_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id integer REFERENCES users (id) ON DELETE CASCADE,
friend_id integer REFERENCES users (id) ON DELETE CASCADE,
friendship_status varchar DEFAULT 'FOR_CONFIRMATION'
);

create table IF NOT EXISTS film (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
film_name varchar NOT NULL,
description varchar(200),
release_date timestamp,
duration integer,
rating_name varchar(10) NOT NULL
);

create table IF NOT EXISTS film_genre (
  film_genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer REFERENCES film (id) ON DELETE CASCADE,
  genre_id integer NOT NULL
);

create table IF NOT EXISTS likes (
  like_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer REFERENCES film (id) ON DELETE CASCADE,
  user_id integer REFERENCES users (id) ON DELETE CASCADE
);




